### ISSUE TITLE
Unable to access /media due to lacking plug permission.

### ISSUE THREAD

**Issue by SuibianP** [predr/typora-snap#2]
First of all, thank you very much for the snap package.

## Short summary

It might be necessary for the `removable-media` plug to be added to `snapcraft.yaml`.

## Long story

I tried accessing a file on a mounted network drive in `/media` but was denied permission despite the subfolder being owned by my user and has 755 permission. Other snap applications such as `vlc` works just fine.

The message in `journalctl` is

```
AVC apparmor="DENIED" operation="open" profile="snap.typora.typora" name=HEXENCODEDDIRECTORYTOFILE pid=26654 comm="Typora" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

It seems that the typora snap does not have the necessary `removable` permission to access `/media` mounts. I tried `snap connect typora:removable-media` but was alerted `error: snap "typora" has no plug named "removable-media"`.

**Comment by predr** [comment]
Added and released Typora with `removable-media`. Refresh and connect plug:

    snap refresh typora
    snap connect typora:removable-media

I might later request to be auto-connected on install but I don't think it will be granted. For now you will have to connect manually.

**Comment by NirmalManoj** [comment]
@predr I think this permission should be enabled by default. I installed typora for the first time yesterday and was surprised to see that I couldn't read/write mounted partitions. (It had access to the Manjaro home partition though). I had to search quite a bit to find this issue and running the command `snap connect typora:removable-media` gave permissions to typora.

Please consider making permission available on install itself, or at least, have a FAQ on the snap description so that people can easily find the fix.

**Comment by predr** [comment]
> making permission available on install itself

Requested auto-connect on snapcraft forum. Will see if they grant it.

> on the snap description so that people can easily find the fix

I don't think it's needed because once you know how permissions work you don't need explanation in every snap description.

![typora-permissions](https://user-images.githubusercontent.com/37021660/115240051-aa690700-a11f-11eb-9ac6-f67c0edfcd04.png)

**Comment by NirmalManoj** [comment]
> I don't think it's needed because once you know how permissions work you don't need explanation in every snap description.

Only once you know how permissions work. I think there are many who don't know this. Why is not having this any better while this is the case?

**Comment by NirmalManoj** [comment]
@predr I use latest Manjaro (xfce). The permissions is not accessible like in the image. At least, I couldn't find it. I assume this is the default state of the package manager in Manjaro XFCE. So I had to use the commands you shared in this thread.
![image](https://user-images.githubusercontent.com/18501167/115670488-17baa900-a367-11eb-9db4-f2d89ea0f12c.png)

**Comment by predr** [comment]
@NirmalManoj I understand this can be a problem for some (I've been there). However, I think we have past the point where _access permissions_ was a novel idea and had to be explained in description boxes. It's on users to learn to use them and on software distributors to make them easy to use.

Image was not meant for you specific case, just to show there are ways for users to discover and use permissions. Work within your community to add this feature if it is missing in your software manager.

**Comment by predr** [comment]
Snap transferred to application author (upstream) and auto-connect will be given to them.
