### ISSUE TITLE
Unable to write in $HOME/bin/ due to lacking plug permission.

### ISSUE THREAD

**Issue by Ro-Lem** [predr/typora-snap#5]
First of all I would like to thank you for providing a Typora Snap package!

Problem description:
Trying to write a file within $HOME/bin/ I got a permission error message: `Error: EACCESS: permission denied, open '/home/<user>/bin/readme.md'`.
Editing and saving the same file with a different editor works.

It seems to me, that adding the `personal-files` plug to the `snapcraft.yaml` and manual connecting this plug may fix this behaviour.
(I tried, but it is not yet supported by the Typora snap.)

Thank you in advance!

**Comment by predr** [comment]
Hi. 👍

~/bin is for user's binary files and bash scripts. If you are placing other non-executable files in there... you are playing with fire as you might accidentally execute those files as scripts.

Access to ~/bin is protected on snaps for security reasons, same as dot directories. While text editors need access to ~/bin because user might wanna edit some scripts, markdown editors don't because there shouldn't be any markdown files in ~/bin.

Also there is approval process for `personal-files` plug and I don't think they would grant me access for reasons above.

**Comment by Ro-Lem** [comment]
Hi,

thank you for your fast feedback and the clarification!

> Access to ~/bin is protected on snaps for security reasons, same as dot directories.
I see, ~/bin/ seems to have a special protection - ~/bin2 for instance works fine.

>  there shouldn't be any markdown files in ~/bin.
I don't agree 100% - think about readme files shipped alongside the binary or script...

In my case, I store some helper-scripts in ~/bin - even if development is still in progress....
Due to this, I have to edit die scripts and the documentation....

I can solve this behavior, by using a different folder in my Home for this purpose.

From my point of view, the issue can be closed.

Thank you again and greetings from Germany!

**Comment by predr** [comment]
> I don't agree 100% - think about readme files shipped alongside the binary or script...

What you wanna do is keep all your files in something like ~/Projects/HelperScripts and symlink your scripts to ~/bin. That way everything will work as intended.
